[plugins]
indra = { id = "net.kyori.indra", version.ref = "indra" }
indra-publishing-gradle-plugin = { id = "net.kyori.indra.publishing.gradle-plugin", version.ref = "indra" }
indra-licenser-spotless = { id = "net.kyori.indra.licenser.spotless", version.ref = "indra" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version = "1.3.1" }

[versions]
ktlint = "0.49.0"
indra = "3.1.3"
configurate = "4.1.2"

[libraries]
configurateYaml = { group = "org.spongepowered", name = "configurate-yaml", version.ref = "configurate" }
configurateGson = { group = "org.spongepowered", name = "configurate-gson", version.ref = "configurate" }

[bundles]
